import json
import os
from datetime import datetime

DATA_FILE = "finance_data.json"

def load_data():
    if os.path.exists(DATA_FILE):
        with open(DATA_FILE, "r") as file:
            return json.load(file)
    return []

def save_data(data):
    with open(DATA_FILE, "w") as file:
        json.dump(data, file, indent=4)

def add_expense():
    try:
        amount = float(input("\nEnter amount: "))
        category = input("Enter category (e.g., Food, Transport, Bills): ").capitalize()
        description = input("Enter brief description: ")
        
      
       entry = {
            "amount": amount,
            "category": category,
            "description": description,
            "date": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        }
        
        data = load_data()
        data.append(entry)
        save_data(data)
        print("✅ Expense added successfully!")
    except ValueError:
        print("❌ Invalid input. Please enter a number for the amount."
        def
